//Week 9: Calculate the message digest of a text using the SHA-512 algorithm.
package week2;

import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

public class Sha {

    public static String encryptThisString(String input) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-512");
            byte[] messageDigest = md.digest(input.getBytes());
            BigInteger no = new BigInteger(1, messageDigest);
            String hashtext = no.toString(16);

            while (hashtext.length() < 128) {
                hashtext = "0" + hashtext;
            }

            return hashtext;
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }

    public static void main(String[] args) {
        System.out.println("HashCode Generated by SHA-512 for:");

        String s1 = "Cryptography";
        System.out.println("\n" + s1 + " : " + encryptThisString(s1));

        String s2 = "Beautiful";
        System.out.println("\n" + s2 + " : " + encryptThisString(s2));
    }
}
